Autorium/OHSB.Web/Controllers/SeatMasterController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.IRepository.SeatMaster;
using Microsoft.Extensions.Configuration;
using OHSB.IRepository.RowMaster;
using OHSB.IRepository.AuditoriumIRepository;
using OHSB.Domain.RowMaster;
using OHSB.Domain.SeatMaster;
using Newtonsoft.Json;

namespace OHSB.Web.Controllers
{
    public class SeatMasterController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly ISeatRepo _Repository;
        private readonly IRowRepository _rowrepo;
        private readonly IAuditoriumRepo _auditoriumrepo;

        public IConfiguration Configuration { get; }
        public SeatMasterController(IHostingEnvironment hostingEnvironment, ISeatRepo repository, IAuditoriumRepo auditoriumRepo, IRowRepository rowrepo, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
            _rowrepo = rowrepo;
            _auditoriumrepo = auditoriumRepo;
        }
        public IActionResult AddSeatInfo()
        {
            ViewBag.AuditoriumID = _auditoriumrepo.GetAll().Result;
            ViewBag.Row_No = _rowrepo.GetAllRows(new RowEntity()).Result;
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> AddSeatInfo(SeatEntity entity)
        {
            try
            {
                if (entity.SeatId != 0)
                {
                    int retMsgd = _Repository.deleteSeatNos(entity.SeatId).Result;
                    int retMg = _Repository.InsertSeat(entity).Result;
                    SeatEntity sp = new SeatEntity();
                    sp = await _Repository.GetseatCapacitybyid(retMg);

                    for (int i = 1; i <= sp.SeatCapacity; i++)
                    {
                        SeatNumbers spp = new SeatNumbers();
                        spp.SeatId = retMg;
                        spp.SeatNos = i;
                        spp.AuditoriumID = entity.AuditoriumID;
                        spp.Row_No = entity.Row_No;
                        int hg = _Repository.insertSeatnos(spp).Result;

                    }
                    return Json("Record updated ");
                }
                else
                {   
                    
                    int retMsg = _Repository.InsertSeat(entity).Result;
                    if (retMsg != -2)
                    {
                        SeatEntity sp = new SeatEntity();
                        sp = await _Repository.GetseatCapacitybyid(retMsg);
                        for (int i = 1; i <= sp.SeatCapacity; i++)
                        {
                            SeatNumbers spp = new SeatNumbers();
                            spp.SeatId = retMsg;
                            spp.SeatNos = i;
                            spp.AuditoriumID = entity.AuditoriumID;
                            spp.Row_No = entity.Row_No;
                            int hg = _Repository.insertSeatnos(spp).Result;

                        }

                        return Json("SeatNos Saved Successfully");
                    }
                  
                }

                return Json("Record Already exist");

            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult ViewSeatInfo()
        {
            ViewBag.AuditoriumID = _auditoriumrepo.GetAll().Result;
            ViewBag.Result = _Repository.GetAllSeat().Result;
            return View();
        }
       
        public IActionResult GetSeat( int AuditoriumID)
        {
            ViewBag.AuditoriumID = AuditoriumID;

            ViewBag.AuditoriumID = _auditoriumrepo.GetAll().Result;
            ViewBag.Resultdata = _Repository.GetSeatdetailsbyid(AuditoriumID).Result;
            return View("ViewSeatInfo");
        }
        [HttpPost]
        public IActionResult DeleteSeat(SeatEntity op)
        {
            try
            {
                int Result = _Repository.deleteSeat(op).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }
        }
        [HttpGet]
        public IActionResult SeatGetById(int SeatId)
        {
            var SubMenus = _Repository.GetSeatbyid(Convert.ToInt32(SeatId)).Result;
            return Ok(JsonConvert.SerializeObject(SubMenus));
        }

        //Demo Seat Design

        public IActionResult DemoSeatDesign()
        {
            ViewBag.AuditoriumID = _auditoriumrepo.GetAll().Result;
            return View();
        }
        [HttpGet]
        public IActionResult SeatNosGetByAuditoriumId(int AuditoriumID)
        {
            var SubMenus = _Repository.GetSeatNosbyid(Convert.ToInt32(AuditoriumID)).Result;
            return Ok(JsonConvert.SerializeObject(SubMenus));
        }
    }
}

Autorium/OHSB.Web/Views/SeatMaster/AddSeatInfo.cshtml
@model OHSB.Domain.SeatMaster.SeatEntity
@{
    ViewData["Title"] = "AddSeatInfo";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
}

<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link active" asp-controller="SeatMaster" asp-action="AddSeatInfo">AddSeat</a>
                    <a class="nav-item nav-link" asp-controller="SeatMaster" asp-action="ViewSeatInfo">ViewSeat</a>
                    <a class="nav-item nav-link " asp-controller="SeatMaster" asp-action="DemoSeatDesign">Demo</a>
                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            <!-- BASIC FORM ELEMENTS -->
            <!--===================================================-->
            <div class="card-body">
                <input type="hidden" value="0" id="hdnSeatId" />
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"><b>Auditorium Name</b><span class="text-danger">*</span></label>
                    <div class="col-xs-12 col-md-4 col-xl-4">
                        <select id="ddlAuditoriumName" class="form-control" asp-items="@(new SelectList(ViewBag.AuditoriumID,"AuditoriumID","AuditoriumName"))" asp-for="AuditoriumID">
                            <option value="0">--Select--</option>
                        </select>
                    </div>

                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"><b>Rows Details</b><span class="text-danger">*</span></label>
                    <div class="col-xs-12 col-md-4 col-xl-4">
                        <select id="ddlRowName" class="form-control" asp-items="@(new SelectList(ViewBag.Row_No,"Row_No","RowDesc"))" asp-for="Row_No">
                            <option value="0">--Select--</option>
                        </select>
                    </div>

                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"><b>SeatCapcity</b> <span class="text-danger">*</span></label>
                    <div class="col-12 col-md-4 col-xl-4">
                        <input type="text" id="txtSeatCapcity" class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"></label>
                    <div class="col-12 col-md-6 col-xl-4">
                        <button class="btn btn-primary mb-1" id="btnSubmit">Submit</button>
                        <button class="btn btn-danger mb-1" id="btnCancel">Reset</button>
                    </div>
                </div>
            </div>
        </div>

        <!--===================================================-->
        <!-- END BASIC FORM ELEMENTS -->
    </div>
</div>
<Script>
    $(document).ready(function () {
        //breadcumb
        loadNavigation('Add Seat', 'gldata', 'plsubmission', 'Add Seat', '', 'Add Seat');
        var SeatId = getUrlVars()["SeatId"];
        if (SeatId != undefined) {
            $("#btnSubmit").html("Update");
            $("#btnCancel").html("Cancel");
            Edit(SeatId);
        }
    });
    $("#btnSubmit").click(function () {
        var dept = {
            SeatId: $("#hdnSeatId").val(),
            AuditoriumID: $("#ddlAuditoriumName").val(),
            Row_No: $("#ddlRowName").val(),
            SeatCapacity: $("#txtSeatCapcity").val()

        };
        if (validate()) {
            if (confirm("Are you sure you want to Submit ?")) {
                $.ajax({
                    url: "/SeatMaster/AddSeatInfo",
                    data: dept,
                    type: "POST",
                    success: function (result) {
                        if (getUrlVars()["SeatId"] != undefined) {
                            alert(result)
                            //window.location.href = "/SubMenu/ViewSubMenu";
                        }
                        else {
                            alert(result);
                            reset();
                        }
                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });
            }
        }
    });

    //reset

    $("#btnCancel").click(function () {
        if ($("#hdnSeatId").val() == '0') {
            reset();
            window.location.href = "/SeatMaster/AddSeatInfo";
           
        }
        else {
            window.location.href = "/SeatMaster/ViewSeatInfo";
            reset();
           
        }

    })
    function reset() {
        $('#hdnSeatId').val("");
        $('#ddlAuditoriumName').val("0");
        $('#ddlRowName').val("0");
        $('#txtSeatCapcity').val("");


    }
    //UPDATE
    function Edit(SeatId) {
        $.ajax({
            url: "/SeatMaster/SeatGetById?SeatId=" + SeatId,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (result) {
                $("#ddlAuditoriumName").val(result.AuditoriumID),
                    $("#ddlRowName").val(result.Row_No),
                    $("#txtSeatCapcity").val(result.SeatCapacity),
                    $("#hdnSeatId").val(result.SeatId)
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
    }
    function validate() {
        if ($('#ddlAuditoriumName').val() == "0") {
            alert("Enter Auditorium Name !");
            return false;
            $('#ddlAuditoriumName').focus();
        }
        else if ($('#ddlRowName').val() == "0") {
            alert("Please RowName type !");
            return false;
            $('#ddlRowName').focus();
        }
        else if ($('#txtSeatCapcity').val() == "") {
            alert("Please enter the seat capacity !");
            return false;
            $('#txtSeatCapcity').focus();
        }      

        else {
            $("#btnReset").hide();
            return true;
        }
    }
</Script>

Autorium/OHSB.Web/Views/SeatMaster/DemoSeatDesign.cshtml
@model OHSB.Domain.SeatMaster.SeatEntity
@{
    ViewData["Title"] = "DemoSeatDesign";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
}
<style>
    .container {
        perspective: 1000px;
        margin-bottom: 30px;
    }

    .screen {
        background-color: #007bff;
        height: 28px;
        width: 40%;
        margin-left: 322px;
        transform: rotatey(1deg);
        box-shadow: 0 3px 10px rgba(255, 255, 255, 0.7);
    }


    /* The container */
    .containerr {
        display: inline;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 16px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

        /* Hide the browser's default checkbox */
    .containerr input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
        height: 0;
        width: 0;
    }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 20px;
        width: 20px;
        background-color: #8080806b;
    }

    /* On mouse-over, add a grey background color */
  /*  .containerr:hover input ~ .checkmark {
        background-color: red;
    }*/

    /* When the checkbox is checked, add a blue background */
    .containerr input:checked ~ .checkmark {
        background-color: #13be62;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .containerr input:checked ~ .checkmark:after {
    }

    /* Style the checkmark/indicator */
    .containerr .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
</style>
<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link " asp-controller="SeatMaster" asp-action="AddSeatInfo">AddSeat</a>
                    <a class="nav-item nav-link" asp-controller="SeatMaster" asp-action="ViewSeatInfo">ViewSeat</a>
                    <a class="nav-item nav-link active" asp-controller="SeatMaster" asp-action="DemoSeatDesign">Booking Seat</a>

                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            @*//  BASIC FORM ELEMENTS BlockMaster/AddBlock
                //  ===================================================*@
            <div class="card-body">
                <div class="form-group row" style="margin-left:315px">
                    <label class="col-12 col-md-2 col-xl-2 control-label"><b>Auditorium</b><span class="text-danger">*</span></label>
                    <div class="col-xs-12 col-md-4 col-xl-4">
                        <select id="ddlAuditorium" onchange="GetRowByAId()" class="form-control" asp-items="@(new SelectList(ViewBag.AuditoriumID,"AuditoriumID","AuditoriumName"))" asp-for="AuditoriumID">
                            <option value="0">--Select--</option>
                        </select>
                    </div>
                </div>
                @*<div class="form-group row">
                        <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input"> Day<span class="text-danger">*</span></label>
                        <div class="col-12 col-md-6 col-xl-4" id="Day">



                        </div>
                    </div>*@
                <div class="container">
                    <ul id="wkslist"></ul>
                    <div class="screen"><center><h5>Screen</h5></center></div>
                    <div id="checkboxlist" style="margin-left:320px">

                    </div>
                </div>

                <div id="checkboxlist">
                    @*<input type="checkbox" id="Tuesday" class="form-control" value="2">*@
                    @*<label for="Tuesday"> Tuesday</label>*@
                </div>
            </div>


            @* ++++++++++++++++++++++++++++++++ *@
            @*<div class="container">
                    <div class="screen"><center><h5>Screen</h5></center></div>


                </div>*@



            @*<div class="text-left mt-2">
                    <button class="btn btn-primary btn-xs mb-2">Available</button>
                    <button class="btn btn-success btn-xs mb-2">Choosen</button>
                    <button class="btn btn-danger btn-xs mb-2">Booked</button>
                </div>*@
            @*//  ===================================================**@
        </div>
    </div>
</div>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script type="text/javascript">
    function GetRowByAId() {
        $.ajax({
            url: "/SeatMaster/SeatNosGetByAuditoriumId?AuditoriumID=" + $('#ddlAuditorium').val(),

            type: "GET",
            success: function (result) {
                data = JSON.parse(result);
                var count = 1;
                var v = '';
                $.each(data, function (i, item) {
                    count++;
                    /* v += '<input type="checkbox" class="seats" name="ck" id="' + (i + 1) + '" value=' + item.SeatNos + ' />' + '<label  for=' + (i + 1) + '>' + item.SeatNos + '</label>';*/
                    v += '<label class="containerr"for=' + (i + 1) + '>' + item.SeatNos +
                        '<input type="checkbox" class="seats" name="ck" id="' + (i + 1) + '" value=' + item.SeatNos + ' />'+
                            '<span class="checkmark"></span>'
                             '</label >'
                    if (count % 10 == 0) { v += '<br/>' }

                });
                $("#checkboxlist").html(v);

            },
            error: function (error) {
                jsonValue = jQuery.parseJSON(error.responseText);
                alert("Error : " + jsonValue);
            }
        });

    }

    //// sample of response from server
    //var response = { optionA: 'One', optionB: 'Two', optionC: 'Three' };

    //// this would go in your ajax success handler
    //$.each(response, function (key, value) {
    //    var li = $('<li><input type="checkbox" name="' + key + '" id="' + key + '"/>' +
    //        '<label for="' + key + '"></label></li>');
    //    li.find('label').text(value);
    //    $('#wkslist').append(li);
    //});
</script>


@*$(":checkbox").click(function () {
        if ($("input:checked").length == ($("#Numseats").val())) {
            $(":checkbox").prop('disabled', true);
            $(':checked').prop('disabled', false);
        }
        else {
            $(":checkbox").prop('disabled', false);
        }
    });*@

Autorium/OHSB.Web/Views/SeatMaster/ViewSeatInfo.cshtml
@model OHSB.Domain.SeatMaster.SeatEntity
@{
    ViewData["Title"] = "ViewSeatInfo";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
    var ResultData = ViewBag.Resultdata as List<OHSB.Domain.SeatMaster.SeatEntity>;
    
}
<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link " asp-controller="SeatMaster" asp-action="AddSeatInfo">AddSeat</a>
                    <a class="nav-item nav-link active" asp-controller="SeatMaster" asp-action="ViewSeatInfo">ViewSeat</a>
                    <a class="nav-item nav-link " asp-controller="SeatMaster" asp-action="DemoSeatDesign">Demo</a>
                </ul>
            </div>
            <div class="card-body">
                <input type="hidden" value="0" id="hdnPermissionId" />
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-xl-2 control-label"><b>Auditorium</b><span class="text-danger">*</span></label>
                    <div class="col-xs-12 col-md-4 col-xl-4">
                        <select id="ddlAuditorium" class="form-control" asp-items="@(new SelectList(ViewBag.AuditoriumID,"AuditoriumID","AuditoriumName",ViewBag.AuditoriumID))">
                            <option value="0">--Select--</option>
                        </select>
                    </div>
                </div>
                <div class="card-body ">
                    @if (ResultData != null && ResultData.ToList().Count > 0)
                    {
                        <div class="table-responsive">
                            <table data-toggle="table" id="tblSubMenu" class="table">
                                <thead>
                                    <tr>
                                        <th width="60px" class="align-top text-center">Sl#</th>
                                        <th width="150px" class="align-top">
                                            Auditorium
                                        </th>
                                        <th width="150px" class="align-top">
                                            Row Name
                                        </th>
                                        <th width="150px" class="align-top">
                                            Seat Capacity
                                        </th>
                                        <th width="150px" class="align-top">
                                            SeatNos
                                        </th>
                                        <th width="150px" class="align-top">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int count = 1;
                                    }
                                    @foreach (var list in ResultData)
                                    {
                                    <tr>
                                        <td class="text-center">@count</td>
                                        <td>
                                            @list.AuditoriumName
                                        </td>
                                        <td>
                                            @list.RowDesc
                                        </td>
                                        <td>
                                            @list.SeatCapacity
                                        </td>
                                        <td>
                                            @list.SeatNo
                                        </td>
                                        <td>
                                            <a onclick="updateSubMenu('@list.SeatId');" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i><b>Edit</b></a><br />
                                            <a onclick="deleteSubMenu('@list.SeatId');" class="text-danger" title="" data-original-title="Delete"><i class="icon-trash-21"></i><b>Delete</b></a>
                                        </td>
                                    </tr>
                                        count++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                    else
                    {
                        <div class="norecord"> No Record Found </div>
                    }
                    <div class="clearfix col-sm-12"></div>
                    @*<div class="form-group row">
                        <label class="col-12 col-md-2 col-xl-2 control-label"></label>
                        <div class="col-12 col-md-6 col-xl-4">
                            <button class="btn btn-primary mb-1" id="btnSubmit">Submit</button>
                            <button class="btn btn-danger mb-1" id="btnCancel">Reset</button>
                        </div>
                    </div>*@
                </div>
                <!--===================================================-->
            </div>
        </div>
</div>
    </div>
<script>
    $(document).ready(function () {
        getDataTable();
    })
     //Auditorium change event to view all the rows and seats
    $("#ddlAuditorium").change(function () {
        location.href = "/SeatMaster/GetSeat?AuditoriumID=" + $("#ddlAuditorium").val();
    });
    //Update Department
    function updateSubMenu(SeatId) {
        if (confirm("Are you sure you want to update ?")) {
            location.href = "/SeatMaster/AddSeatInfo?SeatId=" + SeatId;
        }
    }

    //Delete Department
    function deleteSubMenu(SeatId) {
        if (confirm("Are you sure you want to delete ?")) {
            $.ajax({
                url: "/SeatMaster/DeleteSeat?SeatId=" + SeatId,
                type: "POST",
                dataType: "json",
                contentType: "application/json;charset=UTF-8",
                success: function (data) {
                    if (data == "3") {
                        alert("Record Deleted Successfully");
                        window.location.reload();
                    }
                    else if (data == "-2") {
                        alert("Record Already In Use!");
                        window.location.reload();
                    }
                    else { }
                },
                error: function (error) {
                    jsonValue = jQuery.parseJSON(error.responseText);
                    bootbox.alert("Error : " + jsonValue);
                }
            });
        }
    }

    //Pagination
    function getDataTable() {
        $('#tblSubMenu').DataTable({
            "searching": true,
            //"bStateSave": true,
            "dom": 'Bfrtip',
            "autoWidth": false,
            "buttons": [
                //{
                //    extend: 'print',
                //    title: 'Manage Block',
                //    exportOptions: {
                //        columns: [0, 1, 2, 3, 4]
                //    },
                //    customize: function (win) { $(win.document.body).css('font-size', '10pt').prepend('<img src="' + origin + '/images/t5-logo-white.png"  style="position:absolute; top:0; left:0;" />'); $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit'); }

                //}
                ,
                {
                    extend: 'pageLength'
                }
            ],
            "lengthSubMenu": [
                [10, 25, 50, 100, 1000 - 1],
                ['10 rows', '25 rows', '50 rows', '100 rows', '1000 rows', 'Show all']
            ]
        });
    }
</script>