Autorium/OHSB.Web/Controllers/PriceMasterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.IRepository.PriceMaster;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using OHSB.Domain.PriceMaster;

namespace OHSB.Web.Controllers
{
    public class PriceMasterController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly IPriceRepository _Repository;
        //private readonly IAuditoriumRepo _auditoriumRepo;
        public IConfiguration Configuration { get; }
        public PriceMasterController(IHostingEnvironment hostingEnvironment, IPriceRepository repository, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
            //_auditoriumRepo = auditoriumRepo;
        }
        public async Task<IActionResult> AddPrice( )
        {
            ViewBag.AuditoriumID = _Repository.GetAllAuditorium().Result;           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPrice(PriceEntity doc)
        {
            int retMsg = _Repository.insertupdate(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        [HttpGet]
        public IActionResult GetBlockbyAuditoriumid(int AuditoriumID)
        {
            var client = _Repository.GetAllblock(Convert.ToInt32(AuditoriumID)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }
        [HttpGet]
        public IActionResult GetRowkbyid(int BlockId)
        {
            var client = _Repository.GetAllRow(Convert.ToInt32(BlockId)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }
        public async Task<IActionResult> ViewPrice()
        {

            ViewBag.Result = await _Repository.GetAllPrice();
            return View();

        }
        public IActionResult Delete(PriceEntity ent)
        {
            try
            {
                int Result = _Repository.delete(ent).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult Getbyid(int PriceId)
        {
            var client = _Repository.Getbyid(Convert.ToInt32(PriceId)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }
    }
}

Autorium/OHSB.Web/Views/PriceMaster/AddPrice.cshtml
@model OHSB.Domain.PriceMaster.PriceEntity
@{
    ViewData["Title"] = "AddPrice";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
}
<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link active" asp-controller="PriceMaster" asp-action="AddPrice">AddPrice</a>
                    <a class="nav-item nav-link " asp-controller="PriceMaster" asp-action="ViewPrice">ViewPrice</a>

                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            @*//  BASIC FORM ELEMENTS BlockMaster/AddBlock
                //  ===================================================*@

        <div class="card-body">
            <div class="form-group col-md-4">
                <input id="hdnPriceId" class="form-control" hidden />
            </div>
            <div class="form-group row">
                <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Auditorium <span class="text-danger">*</span></label>
                <div class="col-6 col-md-6 col-xl-4">
                    <select id="ddlAuditorium" onchange="GetBlockByAId()" class="form-control" asp-items="@(new SelectList(ViewBag.AuditoriumID,"AuditoriumID","AuditoriumName"))" asp-for="AuditoriumID">
                        <option value="0">--Select--</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Block <span class="text-danger">*</span></label>
                <div class="col-6 col-md-6 col-xl-4">
                    <select id="ddlBlock" onchange="GetRowById()" class="form-control">
                        <option value="0">--Select--</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Rows<span class="text-danger">*</span></label>
                <div class="col-6 col-md-6 col-xl-4">
                    <select id="ddlRow" class="form-control">
                        <option value="0">--Select--</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-12 col-md-2 col-xl-2 control-label" for="demo-email-input">Price<span class="text-danger">*</span></label>
                <div class="col-6 col-md-6 col-xl-4">
                    <input type="text" id="txtPrice"  class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-12 col-md-2 col-xl-2 control-label"></label>
                <div class="col-12 col-md-6 col-xl-4 justify-content-center">
                    <button class="btn btn-primary mb-1" id="btnSubmit">Submit</button>
                    <button class="btn btn-danger mb-1" id="btnCancel">Reset</button>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        //breadcumb
        loadNavigation('AddPrice', 'gldata', 'plsubmission', 'AddPrice', '', 'AddPrice');
        var PriceId = getUrlVars()["PriceId"];
        if (PriceId != undefined) {
            $("#btnSubmit").html("Update");
            $("#btnCancel").html("Cancel");
            Edit(PriceId)
        }

    });

</script>
<script type="text/javascript">
    function GetBlockByAId() {
        $.ajax({
            url: "/PriceMaster/GetBlockbyAuditoriumid?AuditoriumID=" + $('#ddlAuditorium').val(),
            type: "GET",
            success: function (Result) {
                data = JSON.parse(Result);
                var v = "<option value='0'>--Select--</option>";
                $.each(data, function (i, item) {
                    v += "<option value=" + item.BlockId + ">" + item.BlockName + "</option>";
                });
                $("#ddlBlock").html(v);

            },
            error: function (error) {
                jsonValue = jQuery.parseJSON(error.responseText);
                alert("Error : " + jsonValue);
            }
        });
    }
    function GetRowById() {
        $.ajax({
            url: "/PriceMaster/GetRowkbyid?BlockId=" + $('#ddlBlock').val() ,
            type: "GET",
            success: function (Result) {
                data = JSON.parse(Result);
                var v = "<option value='0'>--Select--</option>";
                $.each(data, function (i, item) {
                    v += "<option value=" + item.Row_No + ">" + item.RowDesc + "</option>";
                });
                $("#ddlRow").html(v);

            },
            error: function (error) {
                jsonValue = jQuery.parseJSON(error.responseText);
                alert("Error : " + jsonValue);
            }
        });
    }
    //insert
    $("#btnSubmit").click(function () {
        var doc = {
            PriceId: $("#hdnPriceId").val(),
            AuditoriumID: $("#ddlAuditorium").val(),
            BlockId: $("#ddlBlock").val(),
            Row_No: $("#ddlRow").val(),
            Price: $("#txtPrice").val()


        };

       if (validate()) {
            //    && NamevalidationC('txtName', 'lblErrorName') == true
            //    && Pricevalidate('price', 'lblerrorprice') == true) {
            if (confirm("Are you sure you want to Submit ?")) {
                $.ajax({
                    url: "/PriceMaster/AddPrice",
                    data: doc,
                    type: "POST",
                    success: function (result) {
                        if (getUrlVars()["PriceId"] != undefined) {
                            alert(result)
                            location.href = "/PriceMaster/ViewPrice";
                        }
                        else
                            alert(result);
                        location.href = "/PriceMaster/ViewPrice";
                        reset();

                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });
            }
        }
        //}

    });
    function fillrows() {
        $.ajax({
            url: "/PriceMaster/GetRowkbyid?BlockId=" + $('#ddlBlock').val(),
            type: "GET",
            success: function (Result) {
                data = JSON.parse(Result);
                var v = "<option value='0'>--Select--</option>";
                $.each(data, function (i, item) {
                    v += "<option value=" + item.Row_No + ">" + item.RowDesc + "</option>";
                });
                $("#ddlRow").html(v);

            },
            error: function (error) {
                jsonValue = jQuery.parseJSON(error.responseText);
                alert("Error : " + jsonValue);
            }
        });
    }
    //UPDATE
    function Edit(PriceId) {
        $.ajax({
            url: "/PriceMaster/Getbyid?PriceId=" + PriceId,
            type: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (Results) {
                $('#hdnPriceId').val(Results.PriceId);
                $('#ddlAuditorium').val(Results.AuditoriumID);             
                //$('#ddlRow').val(Results.Row_No);
                $('#txtPrice').val(Results.Price);
                $.ajax({
                    url: "/PriceMaster/GetBlockbyAuditoriumid?AuditoriumID=" + $('#ddlAuditorium').val(),
                    type: "GET",
                    success: function (Result) {
                        data = JSON.parse(Result);
                        var v = "<option value='0'>--Select--</option>";
                        $.each(data, function (i, item) {
                            v += "<option value=" + item.BlockId + ">" + item.BlockName + "</option>";
                        });
                        $("#ddlBlock").html(v);
                        $('#ddlBlock').val(Results.BlockId);
                        $.ajax({
                            url: "/PriceMaster/GetRowkbyid?BlockId=" + $('#ddlBlock').val(),
                            type: "GET",
                            success: function (Result) {
                                data = JSON.parse(Result);
                                var v = "<option value='0'>--Select--</option>";
                                $.each(data, function (i, item) {
                                    v += "<option value=" + item.Row_No + ">" + item.RowDesc + "</option>";
                                });
                                $("#ddlRow").html(v);
                                $('#ddlRow').val(Results.Row_No);

                            },
                            error: function (error) {
                                jsonValue = jQuery.parseJSON(error.responseText);
                                alert("Error : " + jsonValue);
                            }
                        });
                        

                    },
                    error: function (error) {
                        jsonValue = jQuery.parseJSON(error.responseText);
                        alert("Error : " + jsonValue);
                    }
                });
               

            },
           
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        return false;
    }
    $("#btnCancel").click(function () {
        if ($("#hdnPriceId").val() != '') {
            window.location.href = "/PriceMaster/ViewPrice";
        }
        else
            reset();
    })
    function reset() {
        $('#hdnPriceId').val("");
        $('#ddlAuditorium').val("0");
        $('#ddlBlock').val("0");
        $('#ddlRow').val("0");
        $('#txtPrice').val("");


    }
    //validation
    function validate() {
        if ($('#ddlAuditorium').val() == "0") {
            alert("Please Enter Auditorium!");
            $('#ddlAuditorium').focus();
            return false;
        }
        else if ($('#ddlBlock').val() == "0") {
            alert("Please Enter Block!");
            $('#ddlBlock').focus();
            return false;
        }
        else if ($('#ddlRow').val() == "0") {
            alert("Please Enter Row!");
            $('#ddlRow').focus();
            return false;
        }
        else if ($('#txtPrice').val() == "") {
            alert("Please Enter Price!");
            $('#txtPrice').focus();
            return false;
        }
        else
            return true;
    }
    </script>

Autorium/OHSB.Web/Views/PriceMaster/ViewPrice.cshtml
@model OHSB.Domain.PriceMaster.PriceEntity

@{
    ViewData["Title"] = "ViewPrice";
    Layout = "~/Views/Shared/_LayoutDynamic.cshtml";
    var ResultData = ViewBag.Result as List<OHSB.Domain.PriceMaster.PriceEntity>;
}

<div class="page-title">
    <div class="title-details">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 mb-0 bg-transparent" id="navigation">
            </ol>
        </nav>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs nav-fill" role="tablist">
                    <a class="nav-item nav-link " asp-controller="PriceMaster" asp-action="AddPrice">AddPrice</a>
                    <a class="nav-item nav-link active" asp-controller="PriceMaster" asp-action="ViewPrice">ViewPrice</a>
                </ul>
                <div class="indicatorslist">
                    <a title="" href="javascript:void(0)" id="backIcon" data-toggle="tooltip" data-placement="top" data-original-title="Back"><i class="icon-arrow-left1"></i></a>
                    <p class="ml-2">(*) Indicates mandatory </p>
                </div>
            </div>
            @*//  BASIC FORM ELEMENTS
                //  ===================================================*@
            <div class="card-body ">
                @if (ResultData != null && ResultData.ToList().Count > 0)
                {
                    <div class="table-responsive">
                        <table data-toggle="table" id="tblHospital" class="table">
                            <thead>
                                <tr>
                                    <th width="60px" class="align-top text-center">Sl#</th>
                                    <th width="150px" class="align-top">
                                        Auditorium
                                    </th>
                                    <th width="150px" class="align-top">
                                        Block
                                    </th>
                                    <th width="150px" class="align-top">
                                        Row
                                    </th>
                                    <th width="150px" class="align-top">
                                        Price
                                    </th>
                                    <th width="150px" class="align-top">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @{
                                    int count = 1;
                                }
                                @foreach (var list in ResultData)
                                {
                                <tr>
                                    <td class="text-center">@count</td>
                                    <td>
                                        @list.AuditoriumName
                                    </td>
                                    <td>
                                        @list.BlockName
                                    </td>
                                    <td>
                                        @list.RowDesc
                                    </td>
                                    <td>
                                        @list.Price
                                    </td>
                                    <td>
                                        @*<a href="/HospitalMaster/AddHospital?HospitalID=@Convert.ToString(list.HospitalID)" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i></a>*@
                                        <a onclick="updateDepartment('@list.PriceId');" class="text-primary mr-3" title="" data-original-title="Edit"><i class="icon-edit1"></i><b>Edit</b></a><br />
                                        <a onclick="deleteDoctor('@list.PriceId');" class="text-danger" title="" data-original-title="Delete"><i class="icon-trash-21"></i><b>Delete</b></a>
                                    </td>
                                </tr>
                                    count++;
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="norecord"> No Record Found</div>
                }
                <div class="clearfix col-sm-12"></div>
            </div>
            @*//___________________________________________________________________________*@

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        getDataTable();
    })

    function updateDepartment(PriceId) {
        if (confirm("Are you sure you want to update ?")) {
            location.href = "/PriceMaster/AddPrice?PriceId=" + PriceId;
        }
    }

    function deleteDoctor(PriceId) {
        if (confirm("Are you sure you want to delete ?")) {
            $.ajax({
                url: "/PriceMaster/Delete?PriceId=" + PriceId,
                type: "POST",
                dataType: "json",
                contentType: "application/json;charset=UTF-8",
                success: function (data) {
                    if (data == "3") {
                        alert(" Deleted Successfully");

                        location.href = "/PriceMaster/ViewPrice";

                    }
                    else if (data == "4") {
                        alert(" Already In Use!");

                        location.href = "/PriceMaster/ViewPrice";


                    }
                    else { }
                },
                error: function (error) {
                    jsonValue = jQuery.parseJSON(error.responseText);
                    bootbox.alert("Error : " + jsonValue);
                }
            });
        }
    }
</script>