Autorium/OHSB.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.IRepository.Employee_Master;
using Microsoft.Extensions.Configuration;
using OHSB.Domain.EmployeeMaster;
using OHSB.Domain.AuditoriumMaster;
using OHSB.IRepository.AuditoriumIRepository;
using Newtonsoft.Json;

namespace OHSB.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly IEmployeeRepository  _Repository;
        private readonly IAuditoriumRepo _auditorium;
        public IConfiguration Configuration { get; }
        public EmployeeController(IHostingEnvironment hostingEnvironment, IEmployeeRepository repository, IAuditoriumRepo auditorium,IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
            _auditorium = auditorium;
        }
        public IActionResult AddUser()
        {
            ViewBag.AuditoriumID = _auditorium.GetAll().Result;
            ViewBag.DepartmentId = _Repository.BindDepartment().Result;
            ViewBag.DesignationId = _Repository.BindDesignation().Result;
            ViewBag.RollID = _Repository.BindRole().Result;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(EmployeeEntity doc)
        {
            int retMsg = _Repository.insert(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        public async Task<IActionResult> ViewUser()
        {

            ViewBag.Result = await _Repository.GetAllUser(new EmployeeEntity());
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> ViewUser(EmployeeEntity client)
        {
            ViewBag.Result = await _Repository.GetAllUser(client);
            return View();
        }
        [HttpPost]
        public IActionResult Delete(int Id)
        {
            try
            {
                int Result = _Repository.delete(Id).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult Getbyid(int UserId)
        {
            var client = _Repository.GetbyidUser(Convert.ToInt32(UserId)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }
    }
}

Autorium/OHSB.Web/Controllers/OHSBController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using OHSB.IRepository.OHSB_IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.Domain.OHSB_Master;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;

namespace OHSB.Web.Controllers
{
    public class OHSBController : Controller
    {
        private  IHostingEnvironment _hostingEnvironment;
        private readonly IOHSB_Master _Repository;
        public IConfiguration Configuration { get; }
        public OHSBController(IHostingEnvironment hostingEnvironment, IOHSB_Master repository, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
        }
        public async Task<IActionResult> Add()
        {        
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(OHSB_Entity doc)
        {
            int retMsg = _Repository.CreateDepartMent(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        public async Task<IActionResult> ViewData()
        {
            
            ViewBag.Result = await _Repository.GetAllDepartment();
            return View();
            
        }       
        [HttpPost]
        public IActionResult Delete(OHSB_Entity Id)
        {
            try
            {
                int Result = _Repository.deleteDepartment(Id).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult Getbyid(int DepartmentId)
        {
            var client = _Repository.GetDepartmentbydepartmentId(Convert.ToInt32(DepartmentId)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }


        /////Designation/////////////
        
        public async Task<IActionResult> AddDesignation()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddDesignation(OHSB_Entity doc)
        {
            int retMsg = _Repository.CreateDesignation(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        public async Task<IActionResult> ViewDesignation()
        {

            ViewBag.Result = await _Repository.GetAllDesignation();
            return View();

        }
        [HttpPost]
        public IActionResult DeleteDesignation(OHSB_Entity Id)
        {
            try
            {
                int Result = _Repository.deleteDesignation(Id).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult GetDesigbyid(int DesignationId)
        {
            var client = _Repository.GetDesignationbyDesignationId(Convert.ToInt32(DesignationId)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }


        ////////////////////Role///////////////////////
        public async Task<IActionResult> AddRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(OHSB_Entity doc)
        {
            int retMsg = _Repository.CreateRoll(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        public async Task<IActionResult> ViewRole()
        {

            ViewBag.Result = await _Repository.GetAllRoll();
            return View();

        }
        [HttpPost]
        public IActionResult DeleteRole(OHSB_Entity Id)
        {
            try
            {
                int Result = _Repository.deleteRoll(Id).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult GetRolebyid(int RollID)
        {
            var client = _Repository.GetRollbyRollId(Convert.ToInt32(RollID)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }

    }
}

Autorium/OHSB.Web/Controllers/RowMasterController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.Repository.RowMaster;
using OHSB.IRepository.RowMaster;
using Microsoft.Extensions.Configuration;
using OHSB.Domain.RowMaster;
using Newtonsoft.Json;

namespace OHSB.Web.Controllers
{
    public class RowMasterController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly IRowRepository _Repository;
        public IConfiguration Configuration { get; }
        public RowMasterController(IHostingEnvironment hostingEnvironment, IRowRepository repository, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
        }
        public async Task<IActionResult> AddRow()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddRow(RowEntity doc)
        {
            int retMsg = _Repository.InsertRow(doc).Result;

            if (retMsg == 1)
            {
                return Json("Record Saved Successfully");
            }
            else if (retMsg == 2)
            {
                return Json("Record Updated Successfully");
            }
            else if (retMsg == 3)
            {
                return Json("Record Deleted Successfully");
            }
            else
            {
                return Json("Record Already Exist");
            }
        }
        public async Task<IActionResult> ViewRow()
        {

            ViewBag.Result = await _Repository.GetAllRows(new RowEntity());
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> ViewRow(RowEntity client)
        {
            ViewBag.Result = await _Repository.GetAllRows(client);
            return View();
        }
        [HttpPost]
        public IActionResult Delete(RowEntity Id)
        {
            try
            {
                int Result = _Repository.deleteRow(Id).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

        }
        [HttpGet]
        public IActionResult Getbyid(int Row_No)
        {
            var client = _Repository.GetRowbyid(Convert.ToInt32(Row_No)).Result;
            return Ok(JsonConvert.SerializeObject(client));
        }
        ////seatDetails
        //public async Task<IActionResult> AddSeat()
        //{
        //    ViewBag.Row_No = _Repository.GetAll().Result;
        //    return View();
        //}
        //[HttpPost]
        //public async Task<IActionResult> AddSeat(RowEntity doc)
        //{
        //    int retMsg = _Repository.InsertSeat(doc).Result;

        //    if (retMsg == 1)
        //    {
        //        return Json("Record Saved Successfully");
        //    }
        //    else if (retMsg == 2)
        //    {
        //        return Json("Record Updated Successfully");
        //    }
        //    else if (retMsg == 3)
        //    {
        //        return Json("Record Deleted Successfully");
        //    }
        //    else
        //    {
        //        return Json("Record Already Exist");
        //    }
        //}
        //public async Task<IActionResult> ViewSeatDeatils()
        //{

        //    ViewBag.Result = await _Repository.GetAllSeats(new RowEntity());
        //    return View();

        //}
        //[HttpPost]
        //public async Task<IActionResult> ViewSeatDeatils(RowEntity client)
        //{
        //    ViewBag.Result = await _Repository.GetAllSeats(client);
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult DeleteSeat(RowEntity Id)
        //{
        //    try
        //    {
        //        int Result = _Repository.deleteSeat(Id).Result;
        //        return Json(Result);
        //    }
        //    catch (Exception Ex)
        //    {
        //        throw Ex;
        //    }

        //}
        //[HttpGet]
        //public IActionResult GetSeatbyid(int Seat_Id)
        //{
        //    var client = _Repository.GetSeatbyid(Convert.ToInt32(Seat_Id)).Result;
        //    return Ok(JsonConvert.SerializeObject(client));
        //}
    }
}

Autorium/OHSB.Web/Controllers/SubMenuController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OHSB.IRepository.SubMenuMaster;
using Microsoft.Extensions.Configuration;
using OHSB.IRepository.MenuMaster;
using OHSB.Domain.MenuMaster;
using OHSB.Domain.SubMenuMaster;
using Newtonsoft.Json;

namespace OHSB.Web.Controllers
{
    public class SubMenuController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly ISubMenuRepo _Repository;
        private readonly IMenuRepository _menuRepo;
        public IConfiguration Configuration { get; }
        public SubMenuController(IHostingEnvironment hostingEnvironment, ISubMenuRepo repository,IMenuRepository menuRepo, IConfiguration configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            Configuration = configuration;
            _Repository = repository;
            _menuRepo = menuRepo;
        }
        public IActionResult AddSubMenu()
        {
            ViewBag.Name = _Repository.GetAllMenu().Result;
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> AddSubMenu(SubMenuEntity entity)
        {
            try
            {
                int retMsg = _Repository.SubMenuInsertAndUpdate(entity).Result;

                if (retMsg == 1)
                {
                    return Json("SubMenu Saved Successfully");
                }
                else if (retMsg == 2)
                {
                    return Json("SubMenu Updated Successfully");
                }
                else
                {
                    return Json("SubMenu Already Exist");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public IActionResult ViewSubMenu()
        {
            ViewBag.Result = _Repository.SubMenuSelectAll(new SubMenuEntity()).Result;
            return View();
        }

        [HttpPost]
        public IActionResult DeleteSubMenu(int SubMenuID)
        {
            try
            {
                int Result = _Repository.SubMenuDelete(SubMenuID).Result;
                return Json(Result);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }
        }
        [HttpGet]
        public IActionResult SubMenuGetById(int SubMenuID)
        {
            var SubMenus = _Repository.SubMenuSelectOne(Convert.ToInt32(SubMenuID)).Result;
            return Ok(JsonConvert.SerializeObject(SubMenus));
        }


    }
}

Autorium/OHSB.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OHSB_Master</title>
    <meta name="keywords" content="ADSYS" />
    <meta name="description" content="ADSYS" />
    <link rel="shortcut icon" href="#" type="image/x-icon">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/icons.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/custom.css" rel="stylesheet">
    <link href="~/css/slimscrollbar.min.css" rel="stylesheet">
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/validation/validation.js"></script>
    <script src="~/Datatable/JS/jquery.dataTables.min.js"></script>
    <script src="~/Datatable/JS/dataTables.buttons.js"></script>
    <script src="~/Datatable/JS/buttons.print.js"></script>
    <link href="~/Datatable/CSS/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/Datatable/CSS/jquery.dataTables.min.css" rel="stylesheet" />

    <style>
        .my-nav {
            max-height: 420px;
        }
    </style>


</head>
<body>
    <header>
        <nav class="navbar">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="javascript:void:(0);">
                @*<img src="~/images/Odisha_logo_White.png" alt="Logo">*@
                <h1>
                    OHSB_Master
                    @*<small>Appointment Management System</small>*@
                </h1>
            </a>
            <a class="nav-toggle-btn">
                <span></span>
            </a>
            <!-- Collapse button -->
            <!--   <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#basicExampleNav"
               aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="icon-menu1"></span>
               </button> -->
            <!-- Collapsible content -->
            <div class="navbar-collapse justify-content-end collapse" id="basicExampleNav">
                <!-- Links -->
                <ul class="navbar-nav">
                    <!--  <li class="nav-item">
                       <a class="nav-link" href="<?php echo SITE_PATH; ?>">Home</a>
                       </li>
                       -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false"><i class="icon-bell1"></i> <span class="nobadge">15</span></a>
                        <div class="dropdown-menu notifications" aria-labelledby="navbarDropdownMenuLink">
                            <ul>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                                <li><a>Meeting Scheduled for you.<span>25-Jun-2019</span></a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link setting-link" href="Javascript:void(0);"><i class="icon-settings1"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link logout" href="Javascript:void(0);"><i class="icon-log-out1"></i></a>
                    </li>
                    <!-- Dropdown -->
                </ul>
                <!-- Links -->
            </div>
            <!-- Collapsible content -->
        </nav>
        <!--/.Navbar-->
    </header>
    <div class="logout-modal">
        <div class="logou-container text-center">
            <div class="container">
                <h3>Do you really want to log out?</h3>
                <a class="btn btn-mint" asp-controller="Account" asp-action="Login">Yes</a>
                <a class="btn btn-danger nologout">No</a>
            </div>
        </div>
    </div>
    <div class="page-container">
        <div class="sidemenu" id="dashboard">
            <div class="user-profile">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <img src="~/images/user.png" alt="user"><span>@HttpContextAccessor.HttpContext.Session.GetString("UserName")</span>
                </a>
            </div>
            <div class="clearfix">
            </div>
            <nav class="navbar">
                <div class="navbar-collapse justify-content-end" id="basicExampleNav">
                    <ul class="navbar-nav ">
                        <li class="nav-item dropdown glmaster">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i><span>Master</span></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item plsector" asp-controller="OHSB" asp-action="Add">CommonMaster </a>
                                <a class="dropdown-item plmapping" asp-controller="Employee" asp-action="AddUser">UserRegistration</a>
                                <a class="dropdown-item plmapping" asp-controller="RowMaster" asp-action="AddRow">  RowMaster</a>
                                <a class="dropdown-item pldepartment" asp-controller="AuditoriumMaster" asp-action="AddAuditorium"> AuditoriumMaster</a>
                                <a class="dropdown-item pldepartment" asp-controller="SlotMaster" asp-action="AddSlot"> SlotMaster</a>
                                <a class="dropdown-item plmapping" asp-controller="ShowMaster" asp-action="AddShow">  ShowMaster </a>
                            </div>
                        </li>
                        <li class="nav-item dropdown glmaster">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i><span>Slot Mapping</span></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item plsector" asp-controller="SlotMapping" asp-action="AddSlotMapping">SlotMapping </a>

                            </div>
                        </li>
                        <li class="nav-item dropdown glmaster">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i><span>Authentication</span></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item plsector" asp-controller="MenuMaster" asp-action="AddMenu">Menu Master</a>
                                <a class="dropdown-item plsector" asp-controller="SubMenu" asp-action="AddSubMenu">Add SubMenu</a>
                                <a class="dropdown-item plsector" asp-controller="Permission" asp-action="AddPermission">Add Permission</a>


                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="mainpanel">
            <div class="section">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <p><small>Copyright 2021 PathoLab</small> </p>
    </footer>
    <div class="setting-box">
        <div class="profile-details">
            <a class="setting-close" href="javascript:void(0)"><span class="icon-x1"></span></a>
            <div class="photo__section">
                <img src="images/user.png" alt="user">
                @*<h4>Pragyan Smruty Nayak <small>Admin</small></h4>*@
            </div>
            <div class="change__list">
                <ul>
                    <li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Profile"><span class="icon-user1"></span></a></li>
                    <li><a class="change__list" asp-controller="Account" asp-action="ChangePassword" data-placement="top" data-original-title="Change Password"><span class="icon-lock1"></span></a></li>
                    <li><a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Sign out"><span class="icon-log-out1"></span></a></li>
                </ul>
            </div>
        </div>
        <div class="theme-customizer">
            <h4>Menu option</h4>
            <ul class="menu-option-list">
                <li>
                    Top menu <label class="switch " id="menu-dark">
                        <input type="checkbox" id="topmenucheck" class="default">
                        <span class="slider"></span>
                    </label>
                </li>
                <li>
                    Dark <label class="switch " id="menu-dark">
                        <input type="checkbox" id="darkcheck" class="default">
                        <span class="slider"></span>
                    </label>
                </li>
            </ul>
            <h4>Theme Colors</h4>
            <ul class="theme-list">
                <li><a href="javascript:void(0)" id="custom" class="theme-blue active"></a></li>
                <li><a href="javascript:void(0)" id="theme-sky" class="theme-sky-blue "></a></li>
                <li><a href="javascript:void(0)" id="theme-white" class="theme-white"></a></li>
                <li><a href="javascript:void(0)" id="theme-purple" class="theme-purple "></a></li>
                <li><a href="javascript:void(0)" id="theme-pink" class="theme-pink "></a></li>
                <li><a href="javascript:void(0)" id="theme-orange" class="theme-orange"></a></li>
                <li><a href="javascript:void(0)" id="theme-teal" class="theme-teal "></a></li>
                <li><a href="javascript:void(0)" id="theme-gray" class="theme-gray "></a></li>
            </ul>
        </div>
    </div>
    <link href="~/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="~/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/slimscrollbar.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>
</html>

Autorium/OHSB.Web/Views/Shared/payment.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Domy_Payment_getway</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Domy_Payment_getway</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Domy_Payment_getway - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>